from django.conf.urls import url,include
from.import views

urlpatterns = [
    url(r'^LandingPage', views.LandingPage, name='LandingPage'),
    url(r'^about', views.about, name='about'),
    url(r'^ReadMore', views.ReadMore, name='ReadMore'),
    url(r'^registrationPage', views.registrationPage, name='registrationPage'),
    url(r'^otherRegistrationPage', views.otherRegistrationPage, name='otherRegistrationPage'),
    url(r'^loginPage', views.loginPage, name='loginPage'),
    url(r'^ConfCall',views.ConfCall,name='ConfCall'),
    url(r'^dailyTask', views.dailyTask, name='dailyTask'),
    url(r'^MAN_daily_task', views.MAN_daily_task, name='MAN_daily_task'),
    url(r'^DtACCEPT', views.DtACCEPT, name='DtACCEPT'),
    url(r'^DtREJECT', views.DtREJECT, name='DtREJECT'),
    url(r'^FeedbackDt', views.FeedbackDt, name='FeedbackDt'),
    url(r'^ShowFeedback', views.ShowFeedback, name='ShowFeedback'),
    url(r'^EMPReg', views.EMPReg, name='EMPReg'),
    url(r'^MANReg', views.MANReg, name='MANReg'),
    url(r'^AppLogin', views.AppLogin, name='AppLogin'),
    url(r'^forgotPass', views.forgotPass, name='forgotPass'),
    url(r'^EMPLeaveManagement', views.EMPLeaveManagement, name='EMPLeaveManagement'),
    url(r'^EMPleave', views.EMPleave, name='EMPleave'),
    url(r'^MANleave', views.MANleave, name='MANleave'),
    url(r'^ACCEPTuser', views.ACCEPTuser, name='ACCEPTuser'),
    url(r'^REJECTuser', views.REJECTuser, name='REJECTuser'),
    url(r'^EMP_daily_task', views.EMP_daily_task, name='EMP_daily_task'),
    url(r'^MANLeaveManagement', views.MANLeaveManagement, name='MANLeaveManagement'),
    url(r'^EMPworkingWeekend', views.EMPworkingWeekend, name='EMPworkingWeekend'),
    url(r'^MANworkingWeekend', views.MANworkingWeekend, name='MANworkingWeekend'),
    url(r'^emp_W_W', views.emp_W_W, name='emp_W_W'),
    url(r'^ACCEPT', views.ACCEPT, name='ACCEPT'),
    url(r'^REJECT', views.REJECT, name='REJECT'),
    url(r'^TransportationService', views.TransportationService, name='TransportationService'),
    url(r'^DoTransportationServiceEMP', views.DoTransportationServiceEMP, name='DoTransportationServiceEMP'),
    url(r'^Handling_cab_manager', views.Handling_cab_manager, name='Handling_cab_manager'),
    url(r'^Manager_cab_stauts', views.Manager_cab_stauts, name='Manager_cab_stauts'),
    url(r'^Status_acccept', views.Status_acccept, name='Status_acccept'),
    url(r'^CAB_REJECTED', views.CAB_REJECTED, name='CAB_REJECTED'),
    url(r'^NotesOfConfCall', views.NotesOfConfCall, name='NotesOfConfCall'),
    url(r'^CREATE_NOTE', views.CREATE_NOTE, name='CREATE_NOTE')
]